
jobs:
- name: offline-gen-full-generation
  plan:
  - aggregate:
    {% for resource in git_resources %}
    - get: {{resource['name']}}
    {% endfor %}
    - get: offline-gen-pipeline
    - get: target-pipeline
    - get: offline-gen-param-file
    - get: pipeline-param-file
  - config:
      image_resource:
        source: {repository: nsxedgegen/offline-gen-worker}
        type: docker-image
      inputs:
      - name: offline-gen-pipeline
      - name: target-pipeline
      - name: offline-gen-param-file
      - name: pipeline-param-file
      {% for resource in git_resources %}
      - {name: {{ resource['name'] }} }
      {% endfor %}
      outputs:
      - name: offline-gen-output
      platform: linux
      run:
        args:
        - -exc
        - |
            python offline-gen-pipeline/offline-generator.py -analyze target-pipeline offline-gen-param-file/offline-gen-params*.yml;
            python offline-gen-pipeline/offline-generator.py target-pipeline offline-gen-param-file/offline-gen-params*.yml;
            mv analysis-*  blobstore-*yml offline-*yml offline-gen-output/
            cd offline-gen-output
            for file in $(ls *.yml)
            do
              file_basename=$(basename $file .yml)
              mv ${file} ${file_basename}-1.0.yml
            done
        path: /bin/bash
    task: generate-offline
  - aggregate:
    - put: analysis-results-file-for-((target_pipeline_name))
      params: { file: offline-gen-output/analysis-* }
    - put: blobstore-upload-for-((target_pipeline_name))
      params: { file: offline-gen-output/blobstore-* }
    - put: offline-pipeline-for-((target_pipeline_name))
      params: { file: offline-gen-output/offline-* }

- name: start-blob-upload-for-((target_pipeline_name))
  plan:
  - aggregate:
    - get: pipeline-param-file
    - get: offline-gen-param-file
    - get: blobstore-upload-for-((target_pipeline_name))
      trigger: true
  - put: blobstore-upload-for-((target_pipeline_name))-pipeline
    params:
      pipelines:
      - name: blob-upload-for-((target_pipeline_name))-pipeline
        team: ((concourse_team))
        config_file: blobstore-upload-for-((target_pipeline_name))/*.yml
        vars_files:
        - offline-gen-param-file/offline-gen-param*
        - pipeline-param-file/pipeline-param*

resource_types:
- name: concourse-pipeline
  type: docker-image
  source:
    repository: concourse/concourse-pipeline-resource

resources:
- name: blobstore-upload-for-((target_pipeline_name))-pipeline
  type: concourse-pipeline
  source:
    insecure: "true"
    teams:
    - name: ((concourse_team))
      username: ((concourse_username))
      password: ((concourse_password))

- name: offline-gen-pipeline
  type: git
  source:
    branch: master
    uri: https://github.com/sparameswaran/offline-gen.git

- name: target-pipeline
  type: git
  source:
    branch: {{target_pipeline_branch}}
    uri: {{target_pipeline_uri}}
    #username: username
    #password: password

- name: offline-gen-param-file
  type: s3
  source: {{ offline_gen_param_file_source }}

- name: pipeline-param-file
  type: s3
  source: {{ pipeline_param_file_source }}

- name: analysis-results-file-for-((target_pipeline_name))
  type: s3
  source: {{ analysis_results_filesource }}

- name: blobstore-upload-for-((target_pipeline_name))
  type: s3
  source: {{ blobstore_upload_pipeline_source }}

- name: offline-pipeline-for-((target_pipeline_name))
  type: s3
  source: {{ offline_pipeline_source }}


  {% for resource in git_resources %}
- name: {{ resource['name'] }}
  source: {{ resource['source'] }}
  type: git
  {% endfor %}
