
jobs:
- name: offline-gen-kickoff
  plan:
  - aggregate:
    - get: offline-gen-pipeline
    - get: target-pipeline

  - config:
      image_resource:
        source: {repository: nsxedgegen/offline-gen-worker}
        type: docker-image
      inputs:
      - name: offline-gen-pipeline
      - name: target-pipeline
      outputs:
      - name: offline-gen-output
      platform: linux
      run:
        args:
        - -exc
        - |
            echo ${OFFLINE_GEN_YAML_PARAM} > offline-gen-output/offline-gen-params.yml
            echo ${PIPELINE_YAML_PARAM} > offline-gen-output/pipeline-params.yml
            python offline-gen-pipeline/offline-generator.py -kickoff target-pipeline offline-gen-output/offline-gen-params.yml;
            mv kickoff-*.yml offline-gen-output/
            cd offline-gen-output/
            for file in $(ls *params.yml)
            do
              file_basename=$(basename $file .yml)
              mv ${file} ${file_basename}-1.0.yml
            done
        path: /bin/bash
    task: kickoff-offline-gen
    params:
      OFFLINE_GEN_YAML_PARAM: ((offline_gen_yaml_input_params))
      PIPELINE_YAML_PARAM: ((pipeline_yaml_input_params))
  - aggregate:
    - put: offline-gen-param-file
      params: { file: offline-gen-output/offline-gen-params*.yml }
    - put: pipeline-param-file
      params: { file: offline-gen-output/pipeline-params*.yml }
    - put: kickoff-offline-gen-output
      params: { file: offline-gen-output/kickoff-*.yml }

resource_types:
- name: file-url
  type: docker-image
  source:
    repository: pivotalservices/concourse-curl-resource
    tag: latest

resources:
- name: offline-gen-pipeline
  type: git
  source:
    branch: master
    uri: https://github.com/sparameswaran/offline-gen.git

- name: target-pipeline
  type: git
  source:
    branch: ((target_pipeline_branch))
    uri: ((target_pipeline_uri))

- name: offline-gen-param-file
  type: s3
  source: {{ offline_gen_param_file_source }}

- name: pipeline-param-file
  type: s3
  source: {{ pipeline_param_file_source }}

- name: kickoff-offline-gen-output
  source: {{  kickoff_offline_gen_source }}
  type: s3
